FROM node:22.14.0

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y git netcat-traditional

# Clone all allyabase services
RUN git clone https://www.github.com/freyja-love-and-magic/addie.git addie
RUN git clone https://www.github.com/freyja-love-and-magic/aretha.git aretha
RUN git clone https://www.github.com/freyja-love-and-magic/bdo.git bdo
RUN git clone https://www.github.com/freyja-love-and-magic/continuebee.git continuebee
RUN git clone https://www.github.com/freyja-love-and-magic/dolores.git dolores
RUN git clone https://www.github.com/freyja-love-and-magic/fount.git fount
RUN git clone https://www.github.com/freyja-love-and-magic/joan.git joan
RUN git clone https://www.github.com/freyja-love-and-magic/julia.git julia
RUN git clone https://www.github.com/freyja-love-and-magic/minnie.git minnie
RUN git clone https://www.github.com/freyja-love-and-magic/pref.git pref
RUN git clone https://www.github.com/freyja-love-and-magic/sanora.git sanora
RUN git clone https://www.github.com/freyja-love-and-magic/covenant.git covenant

# Expose all possible ports for 3 bases
# Base 1 (40xx + high ports)
EXPOSE 4000 4001 4002 4003 4004 4005 4006 4007 4011
EXPOSE 3525 3999 8277 8243
# Base 2 (50xx + high ports)
EXPOSE 5000 5001 5002 5003 5004 5005 5006 5007 5011
EXPOSE 4525 4999 9277 9243
# Base 3 (60xx + high ports)
EXPOSE 6000 6001 6002 6003 6004 6005 6006 6007 6011
EXPOSE 5525 5999 10277 10243
# Default ports
EXPOSE 2525 2999 3000 3001 3002 3003 3004 3005 3006 3007 3011 7243 7277

# Install global dependencies
RUN npm install -g pm2 mocha

# Install service dependencies
WORKDIR /usr/src/app/julia/src/server/node
RUN npm install

WORKDIR /usr/src/app/continuebee/src/server/node
RUN npm install

WORKDIR /usr/src/app/joan/src/server/node
RUN npm install

WORKDIR /usr/src/app/pref/src/server/node
RUN npm install

WORKDIR /usr/src/app/bdo/src/server/node
RUN npm install

WORKDIR /usr/src/app/dolores/src/server/node
RUN npm install

WORKDIR /usr/src/app/fount/src/server/node
RUN npm install

WORKDIR /usr/src/app/addie/src/server/node
RUN npm install

WORKDIR /usr/src/app/aretha/src/server/node
RUN npm install

WORKDIR /usr/src/app/sanora/src/server/node
RUN npm install

WORKDIR /usr/src/app/minnie/src/server/node
RUN npm install

WORKDIR /usr/src/app/covenant/src/server/node
RUN npm install

# Install test dependencies for each service
WORKDIR /usr/src/app/addie/test/mocha
RUN npm install

WORKDIR /usr/src/app/aretha/test/mocha
RUN npm install

WORKDIR /usr/src/app/bdo/test/mocha
RUN npm install

WORKDIR /usr/src/app/continuebee/test/mocha
RUN npm install

WORKDIR /usr/src/app/dolores/test/mocha
RUN npm install

WORKDIR /usr/src/app/fount/test/mocha
RUN npm install

WORKDIR /usr/src/app/joan/test/mocha
RUN npm install

WORKDIR /usr/src/app/julia/test/mocha
RUN npm install

WORKDIR /usr/src/app/pref/test/mocha
RUN npm install

WORKDIR /usr/src/app/sanora/test/mocha
RUN npm install

WORKDIR /usr/src/app

# Copy deployment scripts
COPY start-with-ports.sh /usr/src/app/
COPY update-service-ports.sh /usr/src/app/
COPY test-all-services.sh /usr/src/app/
COPY patch-test-urls.sh /usr/src/app/
COPY run-tests-and-services.sh /usr/src/app/

# Make scripts executable
RUN chmod +x /usr/src/app/*.sh

# Update service ports to use environment variables
RUN ./update-service-ports.sh

# Patch test files to use flexible URLs
RUN ./patch-test-urls.sh

# Environment variables
ENV PM2_SAVE_INTERVAL=30000
ENV PM2_LOG_DATE_FORMAT="YYYY-MM-DD HH:mm:ss.SSS"
ENV PORT_OFFSET=0
ENV CONTINUE_ON_FAILURE=false

# Default command runs services and tests
CMD ["./run-tests-and-services.sh"]